### ISSUE TITLE
我操你妈，你为什么盗我号点星星？

### ISSUE THREAD

**Issue by duanNT** [vincentbin/GCS#1]
你脑子有病吧？什么傻逼项目，写的什么玩意，你也配？
你脑子有病吧？什么傻逼项目，写的什么玩意，你也配？
你脑子有病吧？什么傻逼项目，写的什么玩意，你也配？
你脑子有病吧？什么傻逼项目，写的什么玩意，你也配？
你脑子有病吧？什么傻逼项目，写的什么玩意，你也配？

**Comment by vincentbin** [comment]
误会了吧 如果是我盗你号做的这件事我死全家
